### ISSUE TITLE
current deps include a 2.5MB tree

### ISSUE THREAD

**Issue by stefanpenner** [twokul/leek#13]
be sure to audit them, if they are including files that are not needed let them know they should be removed.  

Individually this isn't a problem, but npm's loose de-duping strategy can easily cause a project like `ember-cli` to balloon to many megabytes.

**Comment by twokul** [comment]
@stefanpenner Leek depends on [4 libs](https://github.com/twokul/leek/blob/master/package.json#L30-L33), they're all used. I [dropped](https://github.com/twokul/leek/commit/2a8688e01c7e48c3fcfb7deb15ca8011722314ab) `rewire` as a dependency b/c it was only used in tests.

**Comment by stefanpenner** [comment]
@twokul :+1:
